name: CI

on: [push]

jobs:
  build:
    runs-on: myself-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "Hello, world! iam veeru"
